name = "decklister"
main = "src/index.js"
compatibility_date = "2025-01-10"
account_id = "5af9bf2be24dfe756af55b3bbd542e57"

[assets]
directory = "."
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[[kv_namespaces]]
binding = "DECKLISTEDITOR"
id = "bb576df04a11477f935a3b59ae24ba18"
